export const AVATARS = [
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Felix',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Luna',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Max',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Mia',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Leo',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Sophie',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Oscar',
  'https://api.dicebear.com/7.x/adventurer/svg?seed=Emma',
];

export const SPEED_CONFIG = {
  sekin: { label: "🐢 Sekin", duration: 1500 },
  ortacha: { label: "🚶 O'rtacha", duration: 1000 },
  tez: { label: "🏃 Tez", duration: 500 },
} as const;

export const LEVEL_TERMS = {
  1: { min: 3, max: 4 },
  2: { min: 3, max: 4 },
  3: { min: 4, max: 5 },
  4: { min: 4, max: 5 },
  5: { min: 5, max: 6 },
  6: { min: 5, max: 6 },
  7: { min: 6, max: 7 },
  8: { min: 6, max: 7 },
  9: { min: 6, max: 7 },
  10: { min: 6, max: 7 },
} as const;

export const QUESTIONS_PER_SESSION = 10;
export const BLITZ_TIME_LIMIT = 60; // default 60 seconds for blitz mode
export const BLITZ_DIFFICULTIES = {
  oson: { label: "🟢 Oson", time: 90 },
  ortacha: { label: "🟡 O'rtacha", time: 60 },
  qiyin: { label: "🔴 Qiyin", time: 30 },
} as const;
export const LEVEL_UP_THRESHOLD = 0.7; // 70% accuracy needed

export const MOCK_USER = {
  id: '1',
  uniqueId: 'APEX-12345',
  firstName: 'Ali',
  lastName: 'Karimov',
  birthDate: '2015-05-15',
  avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Leo',
  level: 4,
  xp: 875,
  longestCombo: 21,
  totalQuestions: 342,
  correctAnswers: 315,
  createdAt: '2024-01-15',
  lastActive: new Date().toISOString(),
};

export const MOCK_LEADERBOARD = [
  { rank: 1, user: { name: "Sarvinoz S.", avatarUrl: "https://api.dicebear.com/7.x/adventurer/svg?seed=Sarah" }, elo: 1245, change: 12 },
  { rank: 2, user: { name: "Mirzo M.", avatarUrl: "https://api.dicebear.com/7.x/adventurer/svg?seed=Mike" }, elo: 1180, change: 8 },
  { rank: 3, user: { name: "Nodira N.", avatarUrl: "https://api.dicebear.com/7.x/adventurer/svg?seed=Emma" }, elo: 1120, change: 5 },
];

export const TRAINING_ZONES = [
  // Addition Zones
  {
    id: 'addition-basic',
    title: "Qo'shish: Asosiy",
    description: "100 gacha bo'lgan sonlarni qo'shishni o'rganing.",
    icon: 'Plus',
    color: 'green' as const,
    progress: 100,
    status: 'mastered' as const,
    category: 'addition' as const,
    requiredLevel: 1,
  },
  {
    id: 'addition-advanced',
    title: "Qo'shish: Murakkab",
    description: "1000 gacha bo'lgan sonlarni tez qo'shing.",
    icon: 'Plus',
    color: 'green' as const,
    progress: 75,
    status: 'in-progress' as const,
    category: 'addition' as const,
    requiredLevel: 2,
  },
  // Subtraction Zones
  {
    id: 'subtraction-basic',
    title: "Ayirish: Asosiy",
    description: "100 gacha sonlardan ayirishni o'rganing.",
    icon: 'Minus',
    color: 'blue' as const,
    progress: 100,
    status: 'mastered' as const,
    category: 'subtraction' as const,
    requiredLevel: 2,
  },
  {
    id: 'subtraction-advanced',
    title: "Ayirish: Murakkab",
    description: "Katta sonlardan tez ayirishni mashq qiling.",
    icon: 'Minus',
    color: 'blue' as const,
    progress: 60,
    status: 'in-progress' as const,
    category: 'subtraction' as const,
    requiredLevel: 3,
  },
  // Multiplication Zones
  {
    id: 'multiplication-tables',
    title: "Ko'paytirish Jadvali",
    description: "1-10 gacha ko'paytirish jadvalini o'zlashtiring.",
    icon: 'X',
    color: 'red' as const,
    progress: 30,
    status: 'in-progress' as const,
    category: 'multiplication' as const,
    requiredLevel: 3,
  },
  {
    id: 'multiplication-basic',
    title: "Ko'paytirish: Asosiy",
    description: "2 xonali sonlarni ko'paytiring.",
    icon: 'X',
    color: 'red' as const,
    progress: 0,
    status: 'next-up' as const,
    category: 'multiplication' as const,
    requiredLevel: 4,
  },
  {
    id: 'multiplication-advanced',
    title: "Ko'paytirish: Murakkab",
    description: "3 xonali sonlarni ko'paytirish.",
    icon: 'X',
    color: 'red' as const,
    progress: 0,
    status: 'locked' as const,
    category: 'multiplication' as const,
    requiredLevel: 6,
  },
  // Division Zones
  {
    id: 'division-basic',
    title: "Bo'lish: Asosiy",
    description: "Oddiy bo'lish amallarini o'rganing.",
    icon: 'Divide',
    color: 'gray' as const,
    progress: 0,
    status: 'locked' as const,
    category: 'division' as const,
    requiredLevel: 5,
  },
  {
    id: 'division-advanced',
    title: "Bo'lish: Murakkab",
    description: "Katta sonlarni bo'lishni mashq qiling.",
    icon: 'Divide',
    color: 'gray' as const,
    progress: 0,
    status: 'locked' as const,
    category: 'division' as const,
    requiredLevel: 7,
  },
  {
    id: 'division-remainders',
    title: "Bo'lish: Qoldiqli",
    description: "Qoldiqli bo'lish amallarini o'zlashtiring.",
    icon: 'Divide',
    color: 'gray' as const,
    progress: 0,
    status: 'locked' as const,
    category: 'division' as const,
    requiredLevel: 8,
  },
];

// Mock students for parent/teacher search
export const MOCK_STUDENTS = [
  {
    id: '1',
    uniqueId: 'APEX-12345',
    firstName: 'Ali',
    lastName: 'Karimov',
    birthDate: '2015-05-15',
    avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Leo',
    level: 4,
    xp: 875,
    longestCombo: 21,
    totalQuestions: 342,
    correctAnswers: 315,
    createdAt: '2024-01-15',
    lastActive: new Date().toISOString(),
  },
  {
    id: '2',
    uniqueId: 'APEX-23456',
    firstName: 'Sarvinoz',
    lastName: 'Saidova',
    birthDate: '2014-08-22',
    avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Sarah',
    level: 6,
    xp: 1245,
    longestCombo: 35,
    totalQuestions: 520,
    correctAnswers: 498,
    createdAt: '2023-11-10',
    lastActive: new Date().toISOString(),
  },
  {
    id: '3',
    uniqueId: 'APEX-34567',
    firstName: 'Mirzo',
    lastName: 'Mahmudov',
    birthDate: '2016-02-10',
    avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Mike',
    level: 3,
    xp: 520,
    longestCombo: 15,
    totalQuestions: 180,
    correctAnswers: 156,
    createdAt: '2024-03-20',
    lastActive: new Date().toISOString(),
  },
  {
    id: '4',
    uniqueId: 'APEX-45678',
    firstName: 'Nodira',
    lastName: 'Nazarova',
    birthDate: '2015-11-05',
    avatarUrl: 'https://api.dicebear.com/7.x/adventurer/svg?seed=Emma',
    level: 5,
    xp: 980,
    longestCombo: 28,
    totalQuestions: 410,
    correctAnswers: 385,
    createdAt: '2024-01-08',
    lastActive: new Date().toISOString(),
  },
];

export const ACHIEVEMENTS = [
  { id: '1', name: "Tezlik Ustasi", icon: 'Medal', color: 'text-rank-gold', unlocked: true },
  { id: '2', name: "Mukammal 10", icon: 'Award', color: 'text-category-blue', unlocked: true },
  { id: '3', name: "Aqlli Bola", icon: 'Brain', color: 'text-category-purple', unlocked: true },
  { id: '4', name: "Elektron Tez", icon: 'Zap', color: 'text-category-red', unlocked: true },
  { id: '5', name: "Yulduz", icon: 'Star', color: 'text-rank-gold', unlocked: false },
  { id: '6', name: "Champion", icon: 'Trophy', color: 'text-primary', unlocked: false },
];
